name: Generate TODO.md

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Umožní ruční spuštění workflow

jobs:
  generate-todo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find TODO and FIXME
        run: |
          # Najde všechny TODO a FIXME mimo adresáře začínající tečkou a mimo soubory .md
          grep -rnw --exclude-dir=".*" --exclude="*.md" --exclude="*.tmp" '.' -e "TODO" > todos.tmp || echo "No TODO found."
          grep -rnw --exclude-dir=".*" --exclude="*.md" --exclude="*.tmp" '.' -e "FIXME" > fixmes.tmp || echo "No FIXME found."

      - name: Generate TODO.md in Root
        run: |
          echo "# TODO and FIXME List" > TODO.md
          echo "" >> TODO.md
          
          # Sekce pro TODO
          if [ -s todos.tmp ]; then
            echo "## TODO" >> TODO.md
            awk -F':' '{print $1}' todos.tmp | sort | uniq | while read -r file; do
              echo "" >> TODO.md
              echo "### $file" >> TODO.md
              grep "^$file" todos.tmp | while read -r line; do
                line_number=$(echo "$line" | cut -d':' -f2)
                content=$(echo "$line" | cut -d':' -f3-)
                # Vytvoří položku se zobrazeným číslem řádku a odkazem na konkrétní řádek v GitHubu
                echo "- [ ] Line $line_number: [$content]($file#L$line_number)" >> TODO.md
              done
            done
          else
            echo "No TODO comments found." >> TODO.md
          fi

          echo "" >> TODO.md
          
          # Sekce pro FIXME
          if [ -s fixmes.tmp ]; then
            echo "## FIXME" >> TODO.md
            awk -F':' '{print $1}' fixmes.tmp | sort | uniq | while read -r file; do
              echo "" >> TODO.md
              echo "### $file" >> TODO.md
              grep "^$file" fixmes.tmp | while read -r line; do
                line_number=$(echo "$line" | cut -d':' -f2)
                content=$(echo "$line" | cut -d':' -f3-)
                # Vytvoří položku se zobrazeným číslem řádku a odkazem na konkrétní řádek v GitHubu
                echo "- [ ] Line $line_number: [$content]($file#L$line_number)" >> TODO.md
              done
            done
          else
            echo "No FIXME comments found." >> TODO.md
          fi

      - name: Commit and push TODO.md
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add TODO.md
          git commit -m "Update TODO.md with latest TODO and FIXME comments" || echo "No changes to commit"
          git push --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
